apiVersion: apps/v1
kind: Deployment
metadata:
  name: octopus
spec:
  selector:
    matchLabels:
      app: octopus
  replicas: 2
  template:
    metadata:
      labels:
        app: octopus
    spec:
      containers:
      - name: octopus
        image: <<Your_repo_path_here>>.dkr.ecr.us-east-1.amazonaws.com/octopus_app:latest
        ports:
        - containerPort: 3000