apiVersion: v1

kind: Service

metadata:

  name: redis-service

  labels:

    app: redis

spec:
  type: ClusterIP
  ports:

  - port: 6379
    targetPort: 6379

    name: client


  selector:

    app: redis

---

apiVersion: apps/v1

kind: StatefulSet

metadata:

  name: redis

spec:

  serviceName: redis-service

  replicas: 1

  selector:

    matchLabels:

      app: redis

  template:

    metadata:

      labels:

        app: redis

    spec:

      containers:

      - name: redis

        image: redis:alpine

        ports:

        - containerPort: 6379

          

        volumeMounts:

        - name: data

          mountPath: /redis-master-data
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 500Mi
  volumeClaimTemplates:

  - metadata:

      name: data

    spec:

      accessModes: [ "ReadWriteMany" ]

      resources:

        requests:

          storage: 1Gi


